# Generated by Django 5.1.6 on 2025-03-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='exp',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Average'), (3, 'Decent'), (4, 'Good'), (5, 'Excellent')], default=5),
        ),
    ]
