# Generated by Django 5.1.6 on 2025-03-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_api', '0002_comment_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('head', models.CharField(max_length=100)),
                ('sub_head', models.CharField(max_length=200)),
                ('image_link', models.URLField()),
                ('content', models.TextField()),
                ('sentiment', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Neutral', 'Neutral')], max_length=8)),
            ],
        ),
    ]
