# Generated by Django 5.1.6 on 2025-04-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_api', '0004_alter_news_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sub_head',
            field=models.CharField(max_length=250),
        ),
    ]
